--
-- fmockup - Data Definition Language file
--
-- Date    : 2023-10-01
-- Author  : Hirotoshi FUJIBE
-- History :
--
-- Copyright (c) 2023 Hirotoshi FUJIBE
--

-- Role

DROP ROLE IF EXISTS FMOCKUP_ROLE;
CREATE ROLE FMOCKUP_ROLE;

-- User

DROP USER IF EXISTS 'FMOCKUP_USER'@'localhost';
CREATE USER 'FMOCKUP_USER'@'localhost' IDENTIFIED BY 'Asdf1234' DEFAULT ROLE FMOCKUP_ROLE;

-- Schema

DROP SCHEMA IF EXISTS FMOCKUP;
CREATE SCHEMA FMOCKUP;

-- Tables
--
-- Prefix 'M_' means Maser Data Table
-- Prefix 'S_' means System Fix Value Table
-- Prefix 'T_' meas Transaction Data Table

-- M_USER_LIST

CREATE TABLE FMOCKUP.M_USER_LIST (
	USER_ID						CHAR(26)		NOT NULL UNIQUE,
	USER_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	PASSWORD_AES				VARCHAR(416)	NOT NULL, 									-- 32
	REMARK						VARCHAR(768)	NOT NULL,									-- 128 * 6 = 768
	ROLE_F						CHAR(1)			NOT NULL DEFAULT 'U',
	USER_LOCKED_F				CHAR(1)			NOT NULL DEFAULT 'Y',
	FAILED_COUNT				INTEGER			NOT NULL DEFAULT 0,
	LAST_LOGIN_DATE				CHAR(19)		NOT NULL,
	LAST_CHANGE_PASSWORD_DATE	CHAR(19)		NOT NULL,
	ADD_USER_DATE				CHAR(19)		NOT NULL,
	MODIFY_USER_DATE			CHAR(19)		NOT NULL,
	CREATE_DATE					CHAR(26)		NOT NULL,
	UPDATE_DATE					CHAR(26)		NOT NULL,									-- for Transaciton Control
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( USER_ID, USER_NAME )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.M_USER_LIST TO FMOCKUP_ROLE;

-- M_ROLE_LIST

CREATE TABLE FMOCKUP.M_ROLE_LIST (
	ROLE_ID						CHAR(26)		NOT NULL UNIQUE,
	ROLE_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	REMARK						VARCHAR(768)	NOT NULL,									-- 128 * 6 = 768
	ROLE_F						CHAR(1)			NOT NULL DEFAULT 'U',
	ADD_ROLE_DATE				CHAR(19)		NOT NULL,
	MODIFY_ROLE_DATE			CHAR(19)		NOT NULL,
	CREATE_DATE					CHAR(26)		NOT NULL,
	UPDATE_DATE					CHAR(26)		NOT NULL,									-- for Transaciton Control
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( ROLE_ID, ROLE_NAME )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.M_ROLE_LIST TO FMOCKUP_ROLE;

-- M_USER_ROLE_LIST

CREATE TABLE FMOCKUP.M_USER_ROLE_LIST (
	USER_ID						CHAR(26)		NOT NULL,
	ROLE_ID						CHAR(26)		NOT NULL,
	CREATE_DATE					CHAR(26)		NOT NULL,
	UPDATE_DATE					CHAR(26)		NOT NULL,									-- for Transaciton Control
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( USER_ID, ROLE_ID )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.M_USER_ROLE_LIST TO FMOCKUP_ROLE;

-- M_ROLE_TRAN_LIST

CREATE TABLE FMOCKUP.M_ROLE_TRAN_LIST (
	ROLE_ID						CHAR(26)		NOT NULL,
	TRAN_ID						CHAR(26)		NOT NULL,
	CREATE_DATE					CHAR(26)		NOT NULL,
	UPDATE_DATE					CHAR(26)		NOT NULL,									-- for Transaciton Control
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( ROLE_ID, TRAN_ID )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.M_ROLE_TRAN_LIST TO FMOCKUP_ROLE;

-- S_TRAN_LIST (System Fix Value)

CREATE TABLE FMOCKUP.S_TRAN_LIST (
	TRAN_ID						CHAR(26)		NOT NULL UNIQUE,
	TRAN_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	ROLE_F						CHAR(1)			NOT NULL DEFAULT 'U',
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( TRAN_ID, TRAN_NAME )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.S_TRAN_LIST TO FMOCKUP_ROLE;

-- S_MENU_LIST (System Fix Value)

CREATE TABLE FMOCKUP.S_MENU_LIST (
	MENU_ID						CHAR(26)		NOT NULL UNIQUE,
	MENU_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	TRAN_ID						CHAR(26)		NOT NULL,
	ICON_NAME					VARCHAR(32)		NOT NULL,
	LINK_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	DISP_ORDER              	INTEGER			NOT NULL UNIQUE,
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( MENU_ID, MENU_NAME )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.S_MENU_LIST TO FMOCKUP_ROLE;

-- S_TRAN_TITLE_LIST

CREATE TABLE FMOCKUP.S_TRAN_TITLE_LIST (
	TRAN_ID		CHAR(32)	NOT NULL,
	LANG_ID		VARCHAR(8)	NOT NULL,
	TRAN_TITLE	VARCHAR(16)	NOT NULL,
	PRIMARY KEY(TRAN_ID, LANG_ID)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.S_TRAN_TITLE_LIST TO FMOCKUP_ROLE;

-- T_XXXX_LIST

CREATE TABLE FMOCKUP.T_XXXX_LIST (
	XXXX_ID						CHAR(26)		NOT NULL UNIQUE,
	XXXX_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	XXXX_FLAG					VARCHAR(1)		NOT NULL,
	XXXX_VALUE					VARCHAR(32)		NOT NULL,
	REMARK						VARCHAR(768)	NOT NULL,
	ADD_XXXX_DATE				CHAR(19)		NOT NULL,
	MODIFY_XXXX_DATE			CHAR(19)		NOT NULL,
	CREATE_DATE					CHAR(26)		NOT NULL,
	UPDATE_DATE					CHAR(26)		NOT NULL,									-- for Transaciton Control
	USER_ID						CHAR(26)		NOT NULL,
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( XXXX_ID )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.T_XXXX_LIST TO FMOCKUP_ROLE;

-- T_YYYY_LIST

CREATE TABLE FMOCKUP.T_YYYY_LIST (
	YYYY_ID						CHAR(26)		NOT NULL UNIQUE,
	YYYY_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	YYYY_FLAG					VARCHAR(1)		NOT NULL,
	YYYY_VALUE					VARCHAR(32)		NOT NULL,
	REMARK						VARCHAR(768)	NOT NULL,
	ADD_YYYY_DATE				CHAR(19)		NOT NULL,
	MODIFY_YYYY_DATE			CHAR(19)		NOT NULL,
	CREATE_DATE					CHAR(26)		NOT NULL,
	UPDATE_DATE					CHAR(26)		NOT NULL,									-- for Transaciton Control
	USER_ID						CHAR(26)		NOT NULL,
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( YYYY_ID )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.T_YYYY_LIST TO FMOCKUP_ROLE;

-- T_ZZZZ_LIST

CREATE TABLE FMOCKUP.T_ZZZZ_LIST (
	ZZZZ_ID						CHAR(26)		NOT NULL UNIQUE,
	ZZZZ_NAME					VARCHAR(32)		NOT NULL UNIQUE,
	ZZZZ_FLAG					VARCHAR(1)		NOT NULL,
	ZZZZ_VALUE					VARCHAR(32)		NOT NULL,
	REMARK						VARCHAR(768)	NOT NULL,
	ADD_ZZZZ_DATE				CHAR(19)		NOT NULL,
	MODIFY_ZZZZ_DATE			CHAR(19)		NOT NULL,
	CREATE_DATE					CHAR(26)		NOT NULL,
	UPDATE_DATE					CHAR(26)		NOT NULL,									-- for Transaciton Control
	USER_ID						CHAR(26)		NOT NULL,
	DELETED_F					CHAR(1)			NOT NULL DEFAULT 'N',
	PRIMARY KEY ( ZZZZ_ID )
);
GRANT SELECT, INSERT, UPDATE, DELETE ON FMOCKUP.T_ZZZZ_LIST TO FMOCKUP_ROLE;
